import { resolve, join } from "path";
import { parseOption } from "./cli/args.js";
export const ROOT_PATH = resolve(parseOption("working-dir") ?? ".");
export const SRC_DIR = "src";
export const DIST_DIR = "dist";
export const STATIC_DIR = "static";
export const SRC_PATH = join(ROOT_PATH, SRC_DIR);
export const DIST_PATH = join(ROOT_PATH, DIST_DIR);
export const STATIC_PATH = join(ROOT_PATH, STATIC_DIR);
export const TARGET_DIRS = ["newtab", "popup"];
